name: NHK Radio Download

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade yt-dlp pycryptodomex

      - name: Download NHK Radio
        run: |
          mkdir -p x7k9q2/p01
          yt-dlp \
          --playlist-items -1 \
          --concurrent-fragments 8 \
          --force-overwrites \
          -x \
          --audio-format mp3 \
          "https://www.nhk.or.jp/radio/ondemand/detail.html?p=PMMJ59J6N2_01" \
          -o "x7k9q2/p01/latest.%(ext)s"

          mkdir -p x7k9q2/business-english
          yt-dlp \
          --playlist-items -1 \
          --concurrent-fragments 8 \
          --force-overwrites \
          -x \
          --audio-format mp3 \
          "https://www.nhk.or.jp/radio/ondemand/detail.html?p=368315KKP8_01" \
          -o "x7k9q2/business-english/latest.%(ext)s"

          mkdir -p x7k9q2/gendai-english
          yt-dlp \
          --playlist-items -1 \
          --concurrent-fragments 8 \
          --force-overwrites \
          -x \
          --audio-format mp3 \
          "https://www.nhk.or.jp/radio/ondemand/detail.html?p=77RQWQX1L6_01" \
          -o "x7k9q2/gendai-english/latest.%(ext)s"

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update audio" || exit 0
          git push
